//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MideFrameWork.UI.WebSite.HuaXiaSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/service", ConfigurationName="HuaXiaSms.commonService")]
    public interface commonService {
        
        // CODEGEN: 消息 GetUserInfoRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/common/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/common/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoResponse GetUserInfo(MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoRequest request);
        
        // CODEGEN: 消息 GetUserInfoByChannelRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/common/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/common/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetUserInfoByChannel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelResponse GetUserInfoByChannel(MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelRequest request);
        
        // CODEGEN: 消息 ModifyPasswordRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/common/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/common/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="ModifyPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordResponse ModifyPassword(MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
    public partial class RequestSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string timestampField;
        
        private string transactionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types")]
    public partial class SM_MT_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private string resultTextField;
        
        private string msgIDField;
        
        private double balanceField;
        
        private int submitCountField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
                this.RaisePropertyChanged("ResultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SubmitCount {
            get {
                return this.submitCountField;
            }
            set {
                this.submitCountField = value;
                this.RaisePropertyChanged("SubmitCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types")]
    public partial class SM_MT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long channelField;
        
        private bool channelFieldSpecified;
        
        private string mobileField;
        
        private string contentField;
        
        private string sendTimeField;
        
        private long seqIDField;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("Channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified {
            get {
                return this.channelFieldSpecified;
            }
            set {
                this.channelFieldSpecified = value;
                this.RaisePropertyChanged("ChannelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("SendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long SeqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("SeqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types")]
    public partial class SM_MO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileField;
        
        private string receiveNumberField;
        
        private string contentField;
        
        private string sendtimeField;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiveNumber {
            get {
                return this.receiveNumberField;
            }
            set {
                this.receiveNumberField = value;
                this.RaisePropertyChanged("ReceiveNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sendtime {
            get {
                return this.sendtimeField;
            }
            set {
                this.sendtimeField = value;
                this.RaisePropertyChanged("Sendtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types")]
    public partial class RequestSM_MO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int requestCountField;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RequestCount {
            get {
                return this.requestCountField;
            }
            set {
                this.requestCountField = value;
                this.RaisePropertyChanged("RequestCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
    public partial class Report : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private string resultTextField;
        
        private string mobileField;
        
        private string sendTimeField;
        
        private string receiveTimeField;
        
        private string errorCodeField;
        
        private long seqIDField;
        
        private string msgIDField;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
                this.RaisePropertyChanged("ResultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("SendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReceiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                this.receiveTimeField = value;
                this.RaisePropertyChanged("ReceiveTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long SeqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("SeqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
    public partial class RequestReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int requestCountField;
        
        private string subCodeField;
        
        private long seqIDField;
        
        private string msgIDField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RequestCount {
            get {
                return this.requestCountField;
            }
            set {
                this.requestCountField = value;
                this.RaisePropertyChanged("RequestCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long SeqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("SeqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types")]
    public partial class MM_MT_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private string resultTextField;
        
        private long mM_IDField;
        
        private bool mM_IDFieldSpecified;
        
        private string msgIDField;
        
        private double balanceField;
        
        private int submitCountField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
                this.RaisePropertyChanged("ResultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long MM_ID {
            get {
                return this.mM_IDField;
            }
            set {
                this.mM_IDField = value;
                this.RaisePropertyChanged("MM_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MM_IDSpecified {
            get {
                return this.mM_IDFieldSpecified;
            }
            set {
                this.mM_IDFieldSpecified = value;
                this.RaisePropertyChanged("MM_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SubmitCount {
            get {
                return this.submitCountField;
            }
            set {
                this.submitCountField = value;
                this.RaisePropertyChanged("SubmitCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types")]
    public partial class MM_MT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long channelField;
        
        private bool channelFieldSpecified;
        
        private string mobileField;
        
        private string subjectField;
        
        private MM_Priority priorityField;
        
        private bool withAttachmentField;
        
        private long mM_IDField;
        
        private bool mM_IDFieldSpecified;
        
        private string sendTimeField;
        
        private long seqIDField;
        
        private bool seqIDFieldSpecified;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("Channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified {
            get {
                return this.channelFieldSpecified;
            }
            set {
                this.channelFieldSpecified = value;
                this.RaisePropertyChanged("ChannelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MM_Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool WithAttachment {
            get {
                return this.withAttachmentField;
            }
            set {
                this.withAttachmentField = value;
                this.RaisePropertyChanged("WithAttachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long MM_ID {
            get {
                return this.mM_IDField;
            }
            set {
                this.mM_IDField = value;
                this.RaisePropertyChanged("MM_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MM_IDSpecified {
            get {
                return this.mM_IDFieldSpecified;
            }
            set {
                this.mM_IDFieldSpecified = value;
                this.RaisePropertyChanged("MM_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("SendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long SeqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("SeqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeqIDSpecified {
            get {
                return this.seqIDFieldSpecified;
            }
            set {
                this.seqIDFieldSpecified = value;
                this.RaisePropertyChanged("SeqIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types")]
    public enum MM_Priority {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types")]
    public partial class MM_MO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileField;
        
        private string receiveNumberField;
        
        private string subjectField;
        
        private MM_Priority priorityField;
        
        private string sendTimeField;
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiveNumber {
            get {
                return this.receiveNumberField;
            }
            set {
                this.receiveNumberField = value;
                this.RaisePropertyChanged("ReceiveNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MM_Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("SendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types")]
    public partial class RequestMM_MO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subCodeField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
    public partial class ResponseSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private bool loginStatusField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool LoginStatus {
            get {
                return this.loginStatusField;
            }
            set {
                this.loginStatusField = value;
                this.RaisePropertyChanged("LoginStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double balanceField;
        
        private string corpNameField;
        
        private string userNameField;
        
        private string clientIDField;
        
        private string spNumberField;
        
        private string reverse1Field;
        
        private string reverse2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CorpName {
            get {
                return this.corpNameField;
            }
            set {
                this.corpNameField = value;
                this.RaisePropertyChanged("CorpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpNumber {
            get {
                return this.spNumberField;
            }
            set {
                this.spNumberField = value;
                this.RaisePropertyChanged("SpNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reverse1 {
            get {
                return this.reverse1Field;
            }
            set {
                this.reverse1Field = value;
                this.RaisePropertyChanged("Reverse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reverse2 {
            get {
                return this.reverse2Field;
            }
            set {
                this.reverse2Field = value;
                this.RaisePropertyChanged("Reverse2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader) {
            this.RequestSoapHeader = RequestSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.UserInfo_Result = UserInfo_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoByChannel", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class GetUserInfoByChannelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types", Order=0)]
        public long channel;
        
        public GetUserInfoByChannelRequest() {
        }
        
        public GetUserInfoByChannelRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, long channel) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.channel = channel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoByChannel_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class GetUserInfoByChannelResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result;
        
        public GetUserInfoByChannelResponse() {
        }
        
        public GetUserInfoByChannelResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.UserInfo_Result = UserInfo_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPassword", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class ModifyPasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types", Order=0)]
        public string NewPassword;
        
        public ModifyPasswordRequest() {
        }
        
        public ModifyPasswordRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, string NewPassword) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyPassword_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/common/types", IsWrapped=true)]
    public partial class ModifyPasswordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types", Order=0)]
        public bool ModifyPassword_Result;
        
        public ModifyPasswordResponse() {
        }
        
        public ModifyPasswordResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, bool ModifyPassword_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.ModifyPassword_Result = ModifyPassword_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface commonServiceChannel : MideFrameWork.UI.WebSite.HuaXiaSms.commonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class commonServiceClient : System.ServiceModel.ClientBase<MideFrameWork.UI.WebSite.HuaXiaSms.commonService>, MideFrameWork.UI.WebSite.HuaXiaSms.commonService {
        
        public commonServiceClient() {
        }
        
        public commonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public commonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public commonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public commonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoResponse MideFrameWork.UI.WebSite.HuaXiaSms.commonService.GetUserInfo(MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetUserInfo(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, out MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.commonService)(this)).GetUserInfo(inValue);
            UserInfo_Result = retVal.UserInfo_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelResponse MideFrameWork.UI.WebSite.HuaXiaSms.commonService.GetUserInfoByChannel(MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelRequest request) {
            return base.Channel.GetUserInfoByChannel(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetUserInfoByChannel(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, long channel, out MideFrameWork.UI.WebSite.HuaXiaSms.UserInfo UserInfo_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.channel = channel;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetUserInfoByChannelResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.commonService)(this)).GetUserInfoByChannel(inValue);
            UserInfo_Result = retVal.UserInfo_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordResponse MideFrameWork.UI.WebSite.HuaXiaSms.commonService.ModifyPassword(MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordRequest request) {
            return base.Channel.ModifyPassword(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ModifyPassword(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, string NewPassword, out bool ModifyPassword_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.NewPassword = NewPassword;
            MideFrameWork.UI.WebSite.HuaXiaSms.ModifyPasswordResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.commonService)(this)).ModifyPassword(inValue);
            ModifyPassword_Result = retVal.ModifyPassword_Result;
            return retVal.ResponseSoapHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/service", ConfigurationName="HuaXiaSms.mmsService")]
    public interface mmsService {
        
        // CODEGEN: 消息 GetMM_MORequest 的包装命名空间(http://sdk.worldsms.cn/webservice/mm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/mm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetMM_MO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MOResponse GetMM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MORequest request);
        
        // CODEGEN: 消息 SendMMSRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/mm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/mm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSResponse SendMMS(MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSRequest request);
        
        // CODEGEN: 消息 GetMM_ReportRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/mm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/mm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetMM_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportResponse GetMM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMM_MO", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class GetMM_MORequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestMM_MO RequestMO;
        
        public GetMM_MORequest() {
        }
        
        public GetMM_MORequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestMM_MO RequestMO) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.RequestMO = RequestMO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMM_MO_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class GetMM_MOResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.MM_MO MO_Result;
        
        public GetMM_MOResponse() {
        }
        
        public GetMM_MOResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.MM_MO MO_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.MO_Result = MO_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class SendMMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT MT;
        
        public SendMMSRequest() {
        }
        
        public SendMMSRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT MT) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.MT = MT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class SendMMSResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT_Result MT_Result;
        
        public SendMMSResponse() {
        }
        
        public SendMMSResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT_Result MT_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.MT_Result = MT_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMM_Report", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class GetMM_ReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport;
        
        public GetMM_ReportRequest() {
        }
        
        public GetMM_ReportRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.RequestReport = RequestReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMM_Report_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/mm/types", IsWrapped=true)]
    public partial class GetMM_ReportResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/mm/types", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.Report[] GetReportResult;
        
        public GetMM_ReportResponse() {
        }
        
        public GetMM_ReportResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.Report[] GetReportResult) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mmsServiceChannel : MideFrameWork.UI.WebSite.HuaXiaSms.mmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mmsServiceClient : System.ServiceModel.ClientBase<MideFrameWork.UI.WebSite.HuaXiaSms.mmsService>, MideFrameWork.UI.WebSite.HuaXiaSms.mmsService {
        
        public mmsServiceClient() {
        }
        
        public mmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MOResponse MideFrameWork.UI.WebSite.HuaXiaSms.mmsService.GetMM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MORequest request) {
            return base.Channel.GetMM_MO(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetMM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestMM_MO RequestMO, out MideFrameWork.UI.WebSite.HuaXiaSms.MM_MO MO_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MORequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MORequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.RequestMO = RequestMO;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_MOResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.mmsService)(this)).GetMM_MO(inValue);
            MO_Result = retVal.MO_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSResponse MideFrameWork.UI.WebSite.HuaXiaSms.mmsService.SendMMS(MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSRequest request) {
            return base.Channel.SendMMS(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader SendMMS(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT MT, out MideFrameWork.UI.WebSite.HuaXiaSms.MM_MT_Result MT_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.MT = MT;
            MideFrameWork.UI.WebSite.HuaXiaSms.SendMMSResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.mmsService)(this)).SendMMS(inValue);
            MT_Result = retVal.MT_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportResponse MideFrameWork.UI.WebSite.HuaXiaSms.mmsService.GetMM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportRequest request) {
            return base.Channel.GetMM_Report(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetMM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport, out MideFrameWork.UI.WebSite.HuaXiaSms.Report[] GetReportResult) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.RequestReport = RequestReport;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetMM_ReportResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.mmsService)(this)).GetMM_Report(inValue);
            GetReportResult = retVal.GetReportResult;
            return retVal.ResponseSoapHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/service", ConfigurationName="HuaXiaSms.smsService")]
    public interface smsService {
        
        // CODEGEN: 消息 GetSM_MORequest 的包装命名空间(http://sdk.worldsms.cn/webservice/sm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/sm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetSM_MO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MOResponse GetSM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MORequest request);
        
        // CODEGEN: 消息 SendSMSRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/sm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/sm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSResponse SendSMS(MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSRequest request);
        
        // CODEGEN: 消息 GetSM_ReportRequest 的包装命名空间(http://sdk.worldsms.cn/webservice/sm/types)以后生成的消息协定与默认值(http://sdk.worldsms.cn/webservice/sm/service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="GetSM_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportResponse GetSM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSM_MO", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class GetSM_MORequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSM_MO RequestMO;
        
        public GetSM_MORequest() {
        }
        
        public GetSM_MORequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestSM_MO RequestMO) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.RequestMO = RequestMO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSM_MO_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class GetSM_MOResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MO")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.SM_MO[] MO_Result;
        
        public GetSM_MOResponse() {
        }
        
        public GetSM_MOResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.SM_MO[] MO_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.MO_Result = MO_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT MT;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT MT) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.MT = MT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT_Result MT_Result;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT_Result MT_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.MT_Result = MT_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSM_Report", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class GetSM_ReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        public MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport;
        
        public GetSM_ReportRequest() {
        }
        
        public GetSM_ReportRequest(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport) {
            this.RequestSoapHeader = RequestSoapHeader;
            this.RequestReport = RequestReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSM_Report_Response", WrapperNamespace="http://sdk.worldsms.cn/webservice/sm/types", IsWrapped=true)]
    public partial class GetSM_ReportResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdk.worldsms.cn/webservice/sm/types", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://sdk.worldsms.cn/webservice/common/types")]
        public MideFrameWork.UI.WebSite.HuaXiaSms.Report[] Report_Result;
        
        public GetSM_ReportResponse() {
        }
        
        public GetSM_ReportResponse(MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader ResponseSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.Report[] Report_Result) {
            this.ResponseSoapHeader = ResponseSoapHeader;
            this.Report_Result = Report_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsServiceChannel : MideFrameWork.UI.WebSite.HuaXiaSms.smsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsServiceClient : System.ServiceModel.ClientBase<MideFrameWork.UI.WebSite.HuaXiaSms.smsService>, MideFrameWork.UI.WebSite.HuaXiaSms.smsService {
        
        public smsServiceClient() {
        }
        
        public smsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MOResponse MideFrameWork.UI.WebSite.HuaXiaSms.smsService.GetSM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MORequest request) {
            return base.Channel.GetSM_MO(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetSM_MO(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestSM_MO RequestMO, out MideFrameWork.UI.WebSite.HuaXiaSms.SM_MO[] MO_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MORequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MORequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.RequestMO = RequestMO;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_MOResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.smsService)(this)).GetSM_MO(inValue);
            MO_Result = retVal.MO_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSResponse MideFrameWork.UI.WebSite.HuaXiaSms.smsService.SendSMS(MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader SendSMS(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT MT, out MideFrameWork.UI.WebSite.HuaXiaSms.SM_MT_Result MT_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.MT = MT;
            MideFrameWork.UI.WebSite.HuaXiaSms.SendSMSResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.smsService)(this)).SendSMS(inValue);
            MT_Result = retVal.MT_Result;
            return retVal.ResponseSoapHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportResponse MideFrameWork.UI.WebSite.HuaXiaSms.smsService.GetSM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportRequest request) {
            return base.Channel.GetSM_Report(request);
        }
        
        public MideFrameWork.UI.WebSite.HuaXiaSms.ResponseSoapHeader GetSM_Report(MideFrameWork.UI.WebSite.HuaXiaSms.RequestSoapHeader RequestSoapHeader, MideFrameWork.UI.WebSite.HuaXiaSms.RequestReport RequestReport, out MideFrameWork.UI.WebSite.HuaXiaSms.Report[] Report_Result) {
            MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportRequest inValue = new MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportRequest();
            inValue.RequestSoapHeader = RequestSoapHeader;
            inValue.RequestReport = RequestReport;
            MideFrameWork.UI.WebSite.HuaXiaSms.GetSM_ReportResponse retVal = ((MideFrameWork.UI.WebSite.HuaXiaSms.smsService)(this)).GetSM_Report(inValue);
            Report_Result = retVal.Report_Result;
            return retVal.ResponseSoapHeader;
        }
    }
}
